import numpy as np
from .augmented_block import augmented_block
from .cr import cr
from .factorial import factorial_2
from .gls import greaco_latin_square
from .latin_square import latin_square
from .lattice import lattice
from .rcb import rcb
from .split import split
from .strip import strip
from .youden import youden
